---
title: "EIG Zendo - Plots"
author: "VladG"
date: '2022-12-08'
output: html_document
---

  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(dplyr)

load("./zendo.rdata")
```


```{r}
#Building the trail only data frame 

cert <- c()
rule <- c()
cond <- c()
reach <- c()
ruletype <- c()
rulecount <- c()
id <- c()

j = 0 #counter for the test number within a given trial
i = 1 

while(i <= nrow(selfreport)){
  j = j + 1

  #If this is the test in which certainty has been reached, append the information to our new dataframe and jump to the next trial
  
  if(selfreport$entropy[i] == 0){ 
    cert <- append(cert, selfreport$test[i])            #What test they reached certainty on
    rule <- append(rule, selfreport$rule_nr[i])         #What the rule number is
    ruletype <- append(ruletype, selfreport$rule_re[i]) #What the rule type is
    cond <- append(cond, selfreport$condition[i])       #What the condition is
    reach <- append(reach, "y")                         #Whether they did finally reach certainty
    id <- append(id, selfreport$pid[i])                 #participant ID for random effects modelling
    
    #What the number of objects in the rule is
    if(selfreport$rule_nr[i] %in% c(1,4,7,10,13,16)) rulecount <- append(rulecount, 1)
    else if(selfreport$rule_nr[i] %in% c(2,5,8,11,14,17)) rulecount <- append(rulecount, 2)
    else if(selfreport$rule_nr[i] %in% c(3,6,9,12,15,18)) rulecount <- append(rulecount, 3)

    i <- i + 8 - j 
    j <- 0
  }
  
  #Otherwise, if we reach the end of the trial without ever reaching certainty, do this 
  #(I assumed assigning 9, but perhaps we will find a better solution later)
  
  else if(j == 8){
    cert <- append(cert, 9)
    rule <- append(rule, selfreport$rule_nr[i])
    ruletype <- append(ruletype, selfreport$rule_re[i])
    cond <- append(cond, selfreport$condition[i])
    reach <- append(reach, "n")
    id <- append(id, selfreport$pid[i])                

    
    if(selfreport$rule_nr[i] %in% c(1,4,7,10,13,16)) rulecount <- append(rulecount, 1)
    else if(selfreport$rule_nr[i] %in% c(2,5,8,11,14,17)) rulecount <- append(rulecount, 2)
    else if(selfreport$rule_nr[i] %in% c(3,6,9,12,15,18)) rulecount <- append(rulecount, 3)
    
    j <- 0
  }
  
  i <- i + 1
}
cert <- cert - 1 #remove the example from the test count 

df <- data.frame(cert, rule, cond, reach, ruletype, rulecount,id)
df$rulecount <- as.factor(df$rulecount)
df$ruletype <- as.factor(df$ruletype)
```

```{r}
#Basic Count barplots

ggplot(data = df, aes(x = cond))+
  geom_bar(aes(fill = reach), position = "dodge", color = "black")+
  scale_fill_manual(values = c("black", "white"))+
  #stat_compare_means(comparisons = c())+
  labs(title = "Effect of Condition on Reaching Certainty" , x = "Condition", y = "Nr. of Trials That Reached Certainty")+
  theme_minimal()+
  theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"), panel.grid.major.x = element_blank())+
  theme(axis.title = element_text(size = 15))
```

```{r}
#Mean test number to reach certainty barplots for each condition
ggplot(data = df, aes(x = cond, y = cert, fill = cond))+
  stat_summary(fun.data=mean_sdl, geom="bar", color = "black", position = position_dodge(width = 0.95))+
  stat_summary(fun.data=mean_cl_boot, geom = "errorbar", color = "black", position = position_dodge(width = 0.95), width = 0.3)+
  #scale_fill_manual(values = c("black", "gray", "white"))+
  labs(title = "Effect of Condition on Reaching Certainty" , x = "Condition", y = "Nr. of Trials to Reach Certainty")+
  theme_minimal()+
  theme(axis.title = element_text(size = 15), legend.position = "none")
```

```{r}
#Mean Barplots to reach certainty for each rule
ggplot(data = df, aes(x = reorder(rule, +cert), y = cert))+
  stat_summary(fun.data=mean_sdl, geom="bar", color = "black", position = position_dodge(width = 0.95))+
  stat_summary(fun.data=mean_cl_boot, geom = "errorbar", color = "gray", position = position_dodge(width = 0.95), width = 0.3)+
  scale_fill_manual(values = c("#000000", "#ffffff"))+
  labs(title = "Effect of Rule on Reaching Certainty" , x = "Rule", y = "Nr. of Trials to Reach Certainty")+
  theme_minimal()+
  theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"),
    panel.grid.major.x = element_blank())+
  theme(axis.title = element_text(size = 15))
```

### Plots focused around interactions between the ruletype and condition

```{r}
df_stats <- df %>% 
    group_by(cond, ruletype) %>%
    summarise(
        Avg_Cert = mean(cert), 
        SE = sd(cert) / sqrt(n())
    )

ggplot(data = df_stats, aes(x = cond, y = Avg_Cert, colour = ruletype)) +
    geom_point(size = 3) +
    geom_linerange(aes(ymin = Avg_Cert - 2 * SE, ymax = Avg_Cert + 2 * SE), size = 1) + 
    geom_line(aes(x = as.numeric(cond)), size = 1.2)+
    labs(title = "Interaction Between Rule Type, Condition and Certainty" , x = "Condition", y = "Nr. of Trials to Reach Certainty", colour = "Type of Rule")+
    theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"),
    panel.grid.major.x = element_blank())
```

```{r}
df_stats1 <- df %>% 
    group_by(cond, rulecount) %>%
    summarise(
        Avg_Cert = mean(cert), 
        SE = sd(cert) / sqrt(n())
    )

ggplot(data = df_stats1, aes(x = cond, y = Avg_Cert, colour = rulecount)) +
    geom_point(size = 3) +
    geom_linerange(aes(ymin = Avg_Cert - 2 * SE, ymax = Avg_Cert + 2 * SE), size = 1) + 
    geom_line(aes(x = as.numeric(cond)), size = 1.2)+
    labs(title = "Interaction Between Rock Number in a Rule, Condition and Certainty" , x = "Condition", y = "Nr. of Trials to Reach Certainty", colour = "Nr. of Rocks in the Rule")+
    theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"), 
    panel.grid.major.x = element_blank())
```

```{r}
df_stats2<- df %>% 
    group_by(ruletype, rulecount) %>%
    summarise(
        Avg_Cert = mean(cert), 
        SE = sd(cert) / sqrt(n())
    )

ggplot(data = df_stats2, aes(x = rulecount, y = Avg_Cert, colour = ruletype)) +
    geom_point(size = 3) +
    geom_linerange(aes(ymin = Avg_Cert - 2 * SE, ymax = Avg_Cert + 2 * SE), size = 1) + 
    geom_line(aes(x = as.numeric(rulecount)), size = 1.2)+
    labs(title = "Interaction Between Rock Number in a Rule, Condition and Certainty" , x = "Nr. of Rocks in the Rule", y = "Nr. of Trials to Reach Certainty", colour = "Rule Type")+
    theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"), 
    panel.grid.major.x = element_blank())
```

```{r}
df_stats3 <- df %>% 
    group_by(cond, rule) %>%
    summarise(
        Avg_Cert = mean(cert), 
        SE = sd(cert) / sqrt(n())
    )
ggplot(data = df_stats3, aes(x = cond, y = Avg_Cert, colour = rule)) +
    geom_point(size = 3) +
    #geom_linerange(aes(ymin = Avg_Cert - 2 * SE, ymax = Avg_Cert + 2 * SE)) + 
    geom_line(aes(x = as.numeric(cond)), size = 1.2)+
    labs(title = "Interaction Between Rule Type, Condition and Certainty" , x = "Rule Type", y = "Nr. of Trials to Reach Certainty")+
    theme(panel.background = element_blank(), panel.grid.major = element_line(color = "#DAE1E7"),
    panel.grid.major.x = element_blank())
```

```{r}
  #Timegrowth of certainty proportion
  
  #First, create a dummy dataframe with the percentage of certaint trials for each number of tests bin 
  df$cert <- as.factor(df$cert)
  
  agg_df <- aggregate(df$cond, by=list(df$cert,df$cond), FUN=length, drop = FALSE)
  agg_df[is.na(agg_df)] <-0
  
  perc <- c()
  #All conditions
  c <- append(0,unname(summary(df$cert)))
  perc <- append(perc,cumsum(round(c/sum(c),3) * 100))
  
  #Condition 1
  c <- append(0,agg_df[1:8,3])
  perc <- append(perc,cumsum(round(c/sum(c),3) * 100))
  
  #Condition 2
  c <- append(0,agg_df[9:16,3])
  perc <- append(perc,cumsum(round(c/sum(c),3) * 100))
  
  #Condition 3
  c <- append(0,agg_df[17:24,3])
  perc <- append(perc,cumsum(round(c/sum(c),3) * 100))
  
  
  condition <- c(rep("all",9), rep("1", 9), rep("2",9), rep("3",9))
  test <- c(0:8, 0:8, 0:8, 0:8)
  
  dum <- data.frame(test, perc, condition)
  
  #Note, 5% of all trials never reached certainty 
```

```{r}
dum <- dum %>%  filter(!row_number() %in% c(1, 9, 10, 18, 19, 27, 28, 36)) #remove example and the ones that did not reach certainty

ggplot(dum, aes(x = test, y = perc, color = condition))+
  geom_point()+
  geom_line(size = 1.2)+
  labs(title = "Perecentage of Trials Reaching Certainty Over Number of Tests", y = "Percentage of Trials that Have Reached Certainty", colour = "Research Condition")+
  scale_x_continuous(breaks = c(1:7), name = "Test Number")
```

```{r}
#Repeat, but for condition 2 (object number in the rule)

agg_df2 <- aggregate(df$rulecount, by=list(df$cert,df$rulecount), FUN=length, drop = FALSE)
agg_df2[is.na(agg_df2)] <- 0

perc <- c()
#All conditions
c <- append(0,unname(summary(df$cert)))
perc <- append(perc,cumsum(round(c/sum(c),3) * 100))

#Condition 1
c <- append(0,agg_df2[1:8,3])
perc <- append(perc,cumsum(round(c/sum(c),3) * 100))

#Condition 2
c <- append(0,agg_df2[9:16,3])
perc <- append(perc,cumsum(round(c/sum(c),3) * 100))

#Condition 3
c <- append(0,agg_df2[17:24,3])
perc <- append(perc,cumsum(round(c/sum(c),3) * 100))


condition <- c(rep("all",9), rep("1", 9), rep("2",9), rep("3",9))
test <- c(0:8, 0:8, 0:8, 0:8)

dum2 <- data.frame(test, perc, condition)
```

```{r}
dum2 <- dum2 %>%  filter(!row_number() %in% c(1, 9, 10, 18, 19, 27, 28, 36)) #remove example and the ones that did not reach certainty

ggplot(dum2, aes(x = test, y = perc, color = condition))+
  geom_point()+
  geom_line(size = 1.2)+
  labs(title = "Perecentage of Trials Reaching Certainty Over Number of Tests", y = "Percentage of Trials that Have Reached Certainty", colour = "Number of Objects")+
  scale_x_continuous(breaks = c(1:7), name = "Test Number")
```

```{r}
#Model Analysis, 2x2 ANOVA with the 2 research condition as IV and the nr of tests to reach certainty as DV 

library(lmerTest)

contrasts(df$cond) <- "contr.sum"
contrasts(df$rulecount) <- "contr.sum"

mdl1 <- lmer(as.numeric(cert) ~ cond + rulecount + (1 | id), data = df)
summary(mdl1)

```

- Get some error bars going, run anova/regression, provide p-values 
- Draft for Results section
  - Explain maths behind EIG
  - Breakdown of bulletpoints with attached code